version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
       - "3382:3306"
    networks:
      - private-network

  wordpress:
    depends_on: 
    - db
    image: wordpress:latest
    volumes: 
     - ./:/var/www/html
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
     # - ./wp-content:/var/www/html/wp-content
    ports: 
      - 8170:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
    - private-network 

networks:
    private-network:
        driver: bridge

   
